# Generated by Django 5.0.7 on 2024-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_reason', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('rate', models.IntegerField(max_length=10)),
            ],
        ),
    ]
