# Generated by Django 5.0.7 on 2024-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
