# Generated by Django 5.0.7 on 2024-08-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.restaurant'),
        ),
    ]
